sonar.projectKey=scalecloud_scalecloud.de
sonar.organization=scalecloud
sonar.projectName=scalecloud.de
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/coverage/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info